AWSTemplateFormatVersion: 2010-09-09

Resources:
  SetupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "setup-bucket-${AWS::AccountId}"
      Tags:
        - Key: Name
          Value: SetupBucket
